name: bluesandbox
favicon: null
layout_spectrum: 0.5029083380941302
typography_spectrum: 0.7382018463686109
title: Blue Cat Sandbox
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b060a'
    - '#ffffe9'
    - '#f3bb87'
    - '#762b18'
    - '#ba845e'
  brandStrength: 0.08055405132472515
  lightness: 0.11695757205598056
  saturation: 0.9284758954308927
  rhythmicContrast: 0.9063798543065786
purpose: []
