name: bluesandbox
favicon: null
layout_spectrum: 0.5029083380941302
typography_spectrum: 0.7382018463686109
title: Blue Cat Sandbox
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b90000'
    - '#e9a6a6'
    - '#e28181'
    - '#d75454'
  brandStrength: 0.1875
  lightness: 0.11695757205598056
  saturation: 0.8125
  rhythmicContrast: 0.9063798543065786
purpose: []
